### PR TITLE
Added support for client certificate-based authentication

### PR DESCRIPTION
**Pull request by grogsaxle**
Need client certificate based authentication for newer k8s deployments.  Added optional arguments for the filepaths for the clientKey, clientCert, and caFile.

### CODE REVIEW

**Comment by azweb76** [comment]
awesome, any chance you can move the certs' readFileSync to the construction of the K8sClient? would be more efficient than on a per request basis.

**Comment by grogsaxle** [comment]
Absolutely.  Good eye.

**Comment by azweb76** [comment]
sweet, I'll merge that as soon as you push that change!

**Comment by grogsaxle** [comment]
I'm thinking of pushing the readFileSync out of k8s-client and up into the client.  That removes the requirement that the files are on disk, and enables other delivery methods.  Hashicorp Vault secret delivery comes to mind.

**Comment by azweb76** [comment]
good idea. So clientKey, clientCert, etc become strings, correct? or should I say the contents of the certs.

**Comment by grogsaxle** [comment]
This should take care of it.  I've tested with the contents of the certs being Buffers and strings.  both work just fine.

**Comment by azweb76** [comment]
bumped version and published, thanks!

**Comment by grogsaxle** [comment]
my pleasure.

**Pull request merged**
